<?php

namespace Config;

class StockGroups
{
    const GROUPS_DATA = [
        [
            'name' => 'Bán buôn',
            'list' => [
                [ 'ma' => 'AAT', 'exchange' => 'HOSE', 'des' => 'Bán buôn quần áo, vải và vật tư liên quan' ],
                [ 'ma' => 'AAV', 'exchange' =>  'HNX', 'des' => 'Bán buôn thực phẩm, tạp hóa và các sản phẩm có liên quan' ],
                [ 'ma' => 'ABS', 'exchange' => 'HOSE', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí' ],
                [ 'ma' => 'AMV', 'exchange' =>  'HNX', 'des' => 'Bán buôn các thiết bị, vật tư chuyên môn và thương mại' ],
                [ 'ma' => 'ARM', 'exchange' =>  'HNX', 'des' => 'Bán buôn máy móc, thiết bị và vật tư' ],
                [ 'ma' => 'CKV', 'exchange' =>  'HNX', 'des' => 'Bán buôn máy móc, thiết bị và vật tư' ],
                [ 'ma' => 'CLM', 'exchange' =>  'HNX', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'CMC', 'exchange' =>  'HNX', 'des' => 'Bán buôn máy móc, thiết bị và vật tư' ],
                [ 'ma' => 'CVN', 'exchange' =>  'HNX', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'DBT', 'exchange' => 'HOSE', 'des' => 'Bán buôn dược phẩm và tạp hóa dược' ],
                [ 'ma' => 'DGW', 'exchange' => 'HOSE', 'des' => 'Bán buôn các mặt hàng điện, điện tử' ],
                [ 'ma' => 'DPS', 'exchange' =>  'HNX', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'DXV', 'exchange' => 'HOSE', 'des' => 'Bán buôn gỗ xẻ và vật liệu xây dựng khác' ],
                [ 'ma' => 'FID', 'exchange' =>  'HNX', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'GMA', 'exchange' =>  'HNX', 'des' => 'Bán buôn máy móc, thiết bị và vật tư' ],
                [ 'ma' => 'HAI', 'exchange' => 'HOSE', 'des' => 'Bán buôn hóa chất và các sản phẩm liên quan' ],
                [ 'ma' => 'HAT', 'exchange' =>  'HNX', 'des' => 'Bán buôn bia, rượu, thức uống có cồn' ],
                [ 'ma' => 'HHS', 'exchange' => 'HOSE', 'des' => 'Bán buôn xe cơ giới và phụ tùng xe cơ giới' ],
                [ 'ma' => 'HKB', 'exchange' =>  'HNX', 'des' => 'Bán buôn sản phẩm nuôi trồng thô' ],
                [ 'ma' => 'HMC', 'exchange' => 'HOSE', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'HTL', 'exchange' => 'HOSE', 'des' => 'Bán buôn xe cơ giới và phụ tùng xe cơ giới' ],
                [ 'ma' => 'JVC', 'exchange' => 'HOSE', 'des' => 'Bán buôn các thiết bị, vật tư chuyên môn và thương mại' ],
                [ 'ma' => 'KDM', 'exchange' =>  'HNX', 'des' => 'Bán buôn đồ nội thất và đồ dùng gia đình' ],
                [ 'ma' => 'KLF', 'exchange' =>  'HNX', 'des' => 'Đại lý và môi giới bán buôn điện tử' ],
                [ 'ma' => 'KMT', 'exchange' =>  'HNX', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'MCF', 'exchange' =>  'HNX', 'des' => 'Bán buôn sản phẩm nuôi trồng thô' ],
                [ 'ma' => 'MEL', 'exchange' =>  'HNX', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'PCT', 'exchange' =>  'HNX', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí' ],
                [ 'ma' => 'PET', 'exchange' => 'HOSE', 'des' => 'Bán buôn các mặt hàng điện, điện tử' ],
                [ 'ma' => 'PIT', 'exchange' => 'HOSE', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí' ],
                [ 'ma' => 'PLX', 'exchange' => 'HOSE', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí' ],
                [ 'ma' => 'PMG', 'exchange' => 'HOSE', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí' ],
                [ 'ma' => 'PPY', 'exchange' =>  'HNX', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí' ],
                [ 'ma' => 'PSC', 'exchange' =>  'HNX', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí' ],
                [ 'ma' => 'PSD', 'exchange' =>  'HNX', 'des' => 'Bán buôn các mặt hàng điện, điện tử' ],
                [ 'ma' => 'PSE', 'exchange' =>  'HNX', 'des' => 'Bán buôn hóa chất và các sản phẩm liên quan' ],
                [ 'ma' => 'PSH', 'exchange' => 'HOSE', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí' ],
                [ 'ma' => 'PTB', 'exchange' => 'HOSE', 'des' => 'Bán buôn xe cơ giới và phụ tùng xe cơ giới' ],
                [ 'ma' => 'QBS', 'exchange' => 'HOSE', 'des' => 'Bán buôn hóa chất và các sản phẩm liên quan' ],
                [ 'ma' => 'SGT', 'exchange' => 'HOSE', 'des' => 'Bán buôn các thiết bị, vật tư chuyên môn và thương mại' ],
                [ 'ma' => 'SHN', 'exchange' =>  'HNX', 'des' => 'Bán buôn các mặt hàng tiêu dùng khác' ],
                [ 'ma' => 'SMA', 'exchange' => 'HOSE', 'des' => 'Bán buôn máy móc, thiết bị và vật tư' ],
                [ 'ma' => 'SMC', 'exchange' => 'HOSE', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'SRA', 'exchange' =>  'HNX', 'des' => 'Bán buôn máy móc, thiết bị và vật tư' ],
                [ 'ma' => 'ST8', 'exchange' => 'HOSE', 'des' => 'Bán buôn xe cơ giới và phụ tùng xe cơ giới' ],
                [ 'ma' => 'TCH', 'exchange' => 'HOSE', 'des' => 'Bán buôn xe cơ giới và phụ tùng xe cơ giới' ],
                [ 'ma' => 'TDG', 'exchange' => 'HOSE', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí' ],
                [ 'ma' => 'THS', 'exchange' =>  'HNX', 'des' => 'Bán buôn đồ nội thất và đồ dùng gia đình' ],
                [ 'ma' => 'TLH', 'exchange' => 'HOSE', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'TNA', 'exchange' => 'HOSE', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'TNI', 'exchange' => 'HOSE', 'des' => 'Bán buôn máy móc, thiết bị và vật tư' ],
                [ 'ma' => 'TSC', 'exchange' => 'HOSE', 'des' => 'Bán buôn hóa chất và các sản phẩm liên quan' ],
                [ 'ma' => 'TTB', 'exchange' => 'HOSE', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'TTH', 'exchange' =>  'HNX', 'des' => 'Bán buôn các mặt hàng lâu bền khác' ],
                [ 'ma' => 'UNI', 'exchange' =>  'HNX', 'des' => 'Bán buôn các thiết bị, vật tư chuyên môn và thương mại' ],
                [ 'ma' => 'VFG', 'exchange' => 'HOSE', 'des' => 'Bán buôn hóa chất và các sản phẩm liên quan' ],
                [ 'ma' => 'VID', 'exchange' => 'HOSE', 'des' => 'Bán buôn giấy và các sản phẩm từ giấy' ],
                [ 'ma' => 'VKC', 'exchange' =>  'HNX', 'des' => 'Bán buôn xe cơ giới và phụ tùng xe cơ giới' ],
                [ 'ma' => 'VMD', 'exchange' => 'HOSE', 'des' => 'Bán buôn dược phẩm và tạp hóa dược' ],
                [ 'ma' => 'VPG', 'exchange' => 'HOSE', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
                [ 'ma' => 'VTV', 'exchange' =>  'HNX', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)' ],
            ]
        ],
        [
            'name' => 'Bảo hiểm',
            'list' => [
                [ 'ma' => 'BIC', 'exchange' => 'HOSE', 'des' => 'Hãng bảo hiểm' ],
                [ 'ma' => 'BMI', 'exchange' => 'HOSE', 'des' => 'Hãng bảo hiểm' ],
                [ 'ma' => 'BVH', 'exchange' => 'HOSE', 'des' => 'Hãng bảo hiểm' ],
                [ 'ma' => 'MIG', 'exchange' => 'HOSE', 'des' => 'Hãng bảo hiểm' ],
                [ 'ma' => 'PGI', 'exchange' => 'HOSE', 'des' => 'Hãng bảo hiểm' ],
                [ 'ma' => 'PRE', 'exchange' =>  'HNX', 'des' => 'Hãng bảo hiểm' ],
                [ 'ma' => 'PTI', 'exchange' =>  'HNX', 'des' => 'Hãng bảo hiểm' ],
                [ 'ma' => 'PVI', 'exchange' =>  'HNX', 'des' => 'Hãng bảo hiểm' ],
                [ 'ma' => 'VNR', 'exchange' =>  'HNX', 'des' => 'Hãng bảo hiểm' ],
            ]
        ],
        [
            'name' => 'Bất động sản',
            'list' => [
                [ 'ma' => 'AGG', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'API', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'BAX', 'exchange' =>  'HNX', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'BCE', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'BCM', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'BII', 'exchange' =>  'HNX', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'CCL', 'exchange' => 'HOSE', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'CDC', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'CEO', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'CIG', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'CKG', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'CRE', 'exchange' => 'HOSE', 'des' => 'Đại lý và môi giới bất động sản' ],
                [ 'ma' => 'D11', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'D2D', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'DIG', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'DRH', 'exchange' => 'HOSE', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'DTA', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'DXG', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'EVG', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'FDC', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'FIR', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'FLC', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'HAR', 'exchange' => 'HOSE', 'des' => 'Đại lý và môi giới bất động sản' ],
                [ 'ma' => 'HDC', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'HDG', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'HLD', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'HPX', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'HQC', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'HU1', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'HUT', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'ICG', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'IDV', 'exchange' =>  'HNX', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'IJC', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'ITA', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'ITC', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'KBC', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'KDH', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'KOS', 'exchange' => 'HOSE', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'L14', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'LDG', 'exchange' => 'HOSE', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'LGL', 'exchange' => 'HOSE', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'LHG', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'NBB', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'NDN', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'NHA', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'NLG', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'NRC', 'exchange' =>  'HNX', 'des' => 'Đại lý và môi giới bất động sản' ],
                [ 'ma' => 'NTL', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'NVL', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'PDR', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'PTL', 'exchange' => 'HOSE', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'PV2', 'exchange' =>  'HNX', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'PVL', 'exchange' =>  'HNX', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'PXI', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'QCG', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'RCL', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'SCR', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'SDU', 'exchange' =>  'HNX', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'SGR', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'SIC', 'exchange' =>  'HNX', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'SJC', 'exchange' =>  'HNX', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'SJS', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'SZB', 'exchange' =>  'HNX', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'SZC', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'SZL', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'TDC', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'TDH', 'exchange' => 'HOSE', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'TIG', 'exchange' =>  'HNX', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'TIP', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'TIX', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
                [ 'ma' => 'TN1', 'exchange' => 'HOSE', 'des' => 'Các hoạt động liên quan đến bất động sản' ],
                [ 'ma' => 'VC3', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'VC7', 'exchange' =>  'HNX', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'VHM', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'VIC', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'VPH', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'VPI', 'exchange' => 'HOSE', 'des' => 'Phát triển bất động sản' ],
                [ 'ma' => 'VRC', 'exchange' => 'HOSE', 'des' => 'Đại lý và môi giới bất động sản' ],
                [ 'ma' => 'VRE', 'exchange' => 'HOSE', 'des' => 'Cho thuê bất động sản' ],
            ]
        ],
        [
            'name' => 'Chứng khoán',
            'list' => [
                [ 'ma' => 'AGR', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'APG', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'APS', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'ART', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'BSI', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'BVS', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'CTS', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'EVS', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'FTS', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'HBS', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'HCM', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'IVS', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'MBS', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'PSI', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'SHS', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'SSI', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'TVB', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'TVS', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'VCI', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'VDS', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'VIG', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'VIX', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'VND', 'exchange' => 'HOSE', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
                [ 'ma' => 'WSS', 'exchange' =>  'HNX', 'des' => 'Môi giới chứng khoán và hàng hóa' ],
            ]
        ],
        [
            'name' => 'Công nghệ và thông tin',
            'list' => [
                [ 'ma' => 'ADC', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'BDB', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'BED', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'BST', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'CMG', 'exchange' => 'HOSE', 'des' => 'Các dịch vụ thông tin khác' ],
                [ 'ma' => 'DAD', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'DAE', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'DST', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'EBS', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'ECI', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'EID', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'ELC', 'exchange' => 'HOSE', 'des' => 'Các loại hình viễn thông khác' ],
                [ 'ma' => 'FPT', 'exchange' => 'HOSE', 'des' => 'Sản xuất phần mềm' ],
                [ 'ma' => 'GLT', 'exchange' =>  'HNX', 'des' => 'Các loại hình viễn thông khác' ],
                [ 'ma' => 'HBE', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'HEV', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'ICT', 'exchange' => 'HOSE', 'des' => 'Các loại hình viễn thông khác' ],
                [ 'ma' => 'ITD', 'exchange' => 'HOSE', 'des' => 'Các loại hình viễn thông khác' ],
                [ 'ma' => 'KST', 'exchange' =>  'HNX', 'des' => 'Các loại hình viễn thông khác' ],
                [ 'ma' => 'LBE', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'ONE', 'exchange' =>  'HNX', 'des' => 'Các loại hình viễn thông khác' ],
                [ 'ma' => 'PIA', 'exchange' =>  'HNX', 'des' => 'Các dịch vụ thông tin khác' ],
                [ 'ma' => 'QST', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'SED', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'SGD', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'SMN', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'STC', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'TPH', 'exchange' =>  'HNX', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục' ],
                [ 'ma' => 'VIE', 'exchange' =>  'HNX', 'des' => 'Các loại hình viễn thông khác' ],
                [ 'ma' => 'VTC', 'exchange' =>  'HNX', 'des' => 'Các loại hình viễn thông khác' ],
    
            ]
        ],
        [
            'name' => 'Bán lẻ',
            'list' => [
                [ 'ma' => 'AMD', 'exchange' => 'HOSE', 'des' => 'Kinh doanh vật liệu xây dựng và vật tư liên quan' ],
                [ 'ma' => 'AST', 'exchange' => 'HOSE', 'des' => 'Cửa hàng tổng hợp' ],
                [ 'ma' => 'BTT', 'exchange' => 'HOSE', 'des' => 'Cửa hàng tổng hợp' ],
                [ 'ma' => 'CCI', 'exchange' => 'HOSE', 'des' => 'Trạm xăng có cửa hàng tiện lợi' ],
                [ 'ma' => 'CIA', 'exchange' =>  'HNX', 'des' => 'Các cửa hàng hàng hóa khác' ],
                [ 'ma' => 'CMV', 'exchange' => 'HOSE', 'des' => 'Cửa hàng tổng hợp' ],
                [ 'ma' => 'COM', 'exchange' => 'HOSE', 'des' => 'Trạm xăng có cửa hàng tiện lợi' ],
                [ 'ma' => 'CTC', 'exchange' =>  'HNX', 'des' => 'Cửa hàng sách, ấn bản và âm nhạc' ],
                [ 'ma' => 'CTF', 'exchange' => 'HOSE', 'des' => 'Cửa hàng phụ tùng xe hơi, phụ kiện và săm lốp' ],
                [ 'ma' => 'FRT', 'exchange' => 'HOSE', 'des' => 'Cửa hàng máy tính và phần mềm' ],
                [ 'ma' => 'HAX', 'exchange' => 'HOSE', 'des' => 'Bán lẻ xe hơi' ],
                [ 'ma' => 'HTC', 'exchange' =>  'HNX', 'des' => 'Trạm xăng có cửa hàng tiện lợi' ],
                [ 'ma' => 'MWG', 'exchange' => 'HOSE', 'des' => 'Cửa hàng máy tính và phần mềm' ],
                [ 'ma' => 'NAV', 'exchange' => 'HOSE', 'des' => 'Kinh doanh vật liệu xây dựng và vật tư liên quan' ],
                [ 'ma' => 'PNC', 'exchange' => 'HOSE', 'des' => 'Cửa hàng dụng cụ, văn phòng phẩm và quà tặng' ],
                [ 'ma' => 'SFC', 'exchange' => 'HOSE', 'des' => 'Trạm xăng có cửa hàng tiện lợi' ],
                [ 'ma' => 'SVC', 'exchange' => 'HOSE', 'des' => 'Bán lẻ xe hơi' ],
                [ 'ma' => 'SVN', 'exchange' =>  'HNX', 'des' => 'Kinh doanh vật liệu xây dựng và vật tư liên quan' ],
                [ 'ma' => 'TMC', 'exchange' =>  'HNX', 'des' => 'Trạm xăng có cửa hàng tiện lợi' ],
                [ 'ma' => 'TMX', 'exchange' =>  'HNX', 'des' => 'Kinh doanh vật liệu xây dựng và vật tư liên quan' ],
                [ 'ma' => 'VGC', 'exchange' => 'HOSE', 'des' => 'Kinh doanh vật liệu xây dựng và vật tư liên quan' ],
                [ 'ma' => 'VTJ', 'exchange' =>  'HNX', 'des' => 'Cửa hàng đồ dùng gia đình' ],
            ]
        ],
        [
            'name' => 'Chăm sóc sức khỏe',
            'list' => [
                [ 'ma' => 'DBD', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'DCL', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'DHG', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'DHT', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'DMC', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'DP3', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'FIT', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'IMP', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'LDP', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'MED', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'MKV', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'OPC', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'PMC', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'PME', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'PPP', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'SPM', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'TNH', 'exchange' => 'HOSE', 'des' => 'Các dịch vụ chăm sóc sức khỏe khác' ],
                [ 'ma' => 'TRA', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
                [ 'ma' => 'VDP', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc và dược phẩm' ],
            ]
        ],
        [
            'name' => 'Khai khoáng',
            'list' => [
                [ 'ma' => 'ACM', 'exchange' =>  'HNX', 'des' => 'Khai thác quặng kim loại' ],
                [ 'ma' => 'AMC', 'exchange' =>  'HNX', 'des' => 'Khai thác đá và khoáng sản phi kim' ],
                [ 'ma' => 'ATG', 'exchange' => 'HOSE', 'des' => 'Khai thác quặng kim loại' ],
                [ 'ma' => 'BKC', 'exchange' =>  'HNX', 'des' => 'Khai thác quặng kim loại' ],
                [ 'ma' => 'BMC', 'exchange' => 'HOSE', 'des' => 'Khai thác quặng kim loại' ],
                [ 'ma' => 'C32', 'exchange' => 'HOSE', 'des' => 'Khai thác đá và khoáng sản phi kim' ],
                [ 'ma' => 'DHA', 'exchange' => 'HOSE', 'des' => 'Khai thác đá và khoáng sản phi kim' ],
                [ 'ma' => 'DHM', 'exchange' => 'HOSE', 'des' => 'Khai thác quặng kim loại' ],
                [ 'ma' => 'HGM', 'exchange' =>  'HNX', 'des' => 'Khai thác quặng kim loại' ],
                [ 'ma' => 'HLC', 'exchange' =>  'HNX', 'des' => 'Khai thác than' ],
                [ 'ma' => 'HPM', 'exchange' =>  'HNX', 'des' => 'Khai thác đá và khoáng sản phi kim' ],
                [ 'ma' => 'KSB', 'exchange' => 'HOSE', 'des' => 'Khai thác đá và khoáng sản phi kim' ],
                [ 'ma' => 'KSQ', 'exchange' =>  'HNX', 'des' => 'Khai thác quặng kim loại' ],
                [ 'ma' => 'LCM', 'exchange' => 'HOSE', 'des' => 'Khai thác quặng kim loại' ],
                [ 'ma' => 'MDC', 'exchange' =>  'HNX', 'des' => 'Khai thác than' ],
                [ 'ma' => 'MDG', 'exchange' => 'HOSE', 'des' => 'Khai thác đá và khoáng sản phi kim' ],
                [ 'ma' => 'MIM', 'exchange' =>  'HNX', 'des' => 'Khai thác quặng kim loại' ],
                [ 'ma' => 'MVB', 'exchange' =>  'HNX', 'des' => 'Khai thác đá và khoáng sản phi kim' ],
                [ 'ma' => 'NBC', 'exchange' =>  'HNX', 'des' => 'Khai thác than' ],
                [ 'ma' => 'NNC', 'exchange' => 'HOSE', 'des' => 'Khai thác đá và khoáng sản phi kim' ],
                [ 'ma' => 'PVB', 'exchange' =>  'HNX', 'des' => 'Các hoạt động hỗ trợ cho khai thác dầu và khí đốt' ],
                [ 'ma' => 'PVC', 'exchange' =>  'HNX', 'des' => 'Các hoạt động hỗ trợ cho khai thác dầu và khí đốt' ],
                [ 'ma' => 'PVD', 'exchange' => 'HOSE', 'des' => 'Khoan giếng dầu và khí đốt' ],
                [ 'ma' => 'PVS', 'exchange' =>  'HNX', 'des' => 'Các hoạt động hỗ trợ cho khai thác dầu và khí đốt' ],
                [ 'ma' => 'SPI', 'exchange' =>  'HNX', 'des' => 'Khai thác đá và khoáng sản phi kim' ],
                [ 'ma' => 'TC6', 'exchange' =>  'HNX', 'des' => 'Khai thác than' ],
                [ 'ma' => 'TDN', 'exchange' =>  'HNX', 'des' => 'Khai thác than' ],
                [ 'ma' => 'THT', 'exchange' =>  'HNX', 'des' => 'Khai thác than' ],
                [ 'ma' => 'TMB', 'exchange' =>  'HNX', 'des' => 'Khai thác than' ],
                [ 'ma' => 'TNT', 'exchange' => 'HOSE', 'des' => 'Khai thác quặng kim loại' ],
                [ 'ma' => 'TVD', 'exchange' =>  'HNX', 'des' => 'Khai thác than' ],
            ]
        ],
        [
            'name' => 'Ngân hàng',
            'list' => [
                [ 'ma' => 'ACB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'BAB', 'exchange' =>  'HNX', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'BID', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'CTG', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'EIB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'HDB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'LPB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'MBB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'MSB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'NVB', 'exchange' =>  'HNX', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'OCB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'SHB', 'exchange' =>  'HNX', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'SSB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'STB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'TCB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'TPB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'VCB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'VIB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
                [ 'ma' => 'VPB', 'exchange' => 'HOSE', 'des' => 'Trung gian tín dụng có nhận tiền gửi' ],
            ]
        ],
        [
            'name' => 'Nông - Lâm - Ngư',
            'list' => [
                [ 'ma' => 'APC', 'exchange' => 'HOSE', 'des' => 'Các hoạt động hỗ trợ cho trồng trọt' ],
                [ 'ma' => 'ASM', 'exchange' => 'HOSE', 'des' => 'Nuôi trồng thủy sản' ],
                [ 'ma' => 'CTP', 'exchange' =>  'HNX', 'des' => 'Trồng trọt cây có hạt và các loại trái cây' ],
                [ 'ma' => 'HAG', 'exchange' => 'HOSE', 'des' => 'Trồng trọt cây có hạt và các loại trái cây' ],
                [ 'ma' => 'HKT', 'exchange' =>  'HNX', 'des' => 'Trồng trọt các loại cây khác' ],
                [ 'ma' => 'HNG', 'exchange' => 'HOSE', 'des' => 'Trồng trọt các loại cây khác' ],
                [ 'ma' => 'HSL', 'exchange' => 'HOSE', 'des' => 'Trồng trọt cây lương thực và các loại hạt có dầu' ],
                [ 'ma' => 'NSC', 'exchange' => 'HOSE', 'des' => 'Trồng trọt các loại cây khác' ],
                [ 'ma' => 'PSW', 'exchange' =>  'HNX', 'des' => 'Các hoạt động hỗ trợ cho trồng trọt' ],
                [ 'ma' => 'SJF', 'exchange' => 'HOSE', 'des' => 'Trồng trọt các loại cây khác' ],
                [ 'ma' => 'SSC', 'exchange' => 'HOSE', 'des' => 'Trồng trọt các loại cây khác' ],
                [ 'ma' => 'VIF', 'exchange' =>  'HNX', 'des' => 'Trồng rừng lấy gỗ' ],
            ]
        ],
        [
            'name' => 'SX Thiết bị, máy móc',
            'list' => [
                [ 'ma' => 'CJC', 'exchange' =>  'HNX', 'des' => 'Sản xuất động cơ, tua bin và thiết bị truyền tải điện' ],
                [ 'ma' => 'CTB', 'exchange' =>  'HNX', 'des' => 'Sản xuất thiết bị nông nghiệp, xây dựng và khai khoáng' ],
                [ 'ma' => 'CTT', 'exchange' =>  'HNX', 'des' => 'Sản xuất thiết bị, máy móc công nghiệp' ],
                [ 'ma' => 'DZM', 'exchange' =>  'HNX', 'des' => 'Sản xuất thiết bị, máy móc công nghiệp' ],
                [ 'ma' => 'MCG', 'exchange' => 'HOSE', 'des' => 'Sản xuất thiết bị nông nghiệp, xây dựng và khai khoáng' ],
                [ 'ma' => 'NAG', 'exchange' =>  'HNX', 'des' => 'Sản xuất hệ thống thông gió, sưởi ấm, điều hòa nhiệt độ và thiết bị làm lạnh' ],
                [ 'ma' => 'NHH', 'exchange' => 'HOSE', 'des' => 'Sản xuất thiết bị, máy móc công nghiệp' ],
                [ 'ma' => 'QHD', 'exchange' =>  'HNX', 'des' => 'Sản xuất thiết bị nông nghiệp, xây dựng và khai khoáng' ],
                [ 'ma' => 'SHE', 'exchange' =>  'HNX', 'des' => 'Sản xuất máy móc công nghiệp dịch vụ và thương mại' ],
                [ 'ma' => 'THI', 'exchange' => 'HOSE', 'des' => 'Sản xuất thiết bị, máy móc công nghiệp' ],
            ]
        ],
        [
            'name' => 'SX Hàng gia dụng',
            'list' => [
                [ 'ma' => 'ADS', 'exchange' => 'HOSE', 'des' => 'Sản xuất sợi, vải thành phẩm' ],
                [ 'ma' => 'EVE', 'exchange' => 'HOSE', 'des' => 'Sản xuất phụ kiện và các sản phẩm may mặc khác' ],
                [ 'ma' => 'FTM', 'exchange' => 'HOSE', 'des' => 'Sản xuất sợi' ],
                [ 'ma' => 'GDT', 'exchange' => 'HOSE', 'des' => 'Sản xuất tủ bếp và nội thất hộ gia đình' ],
                [ 'ma' => 'GIL', 'exchange' => 'HOSE', 'des' => 'Sản xuất phụ kiện và các sản phẩm may mặc khác' ],
                [ 'ma' => 'GMC', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp' ],
                [ 'ma' => 'KMR', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm dệt dùng trong nhà' ],
                [ 'ma' => 'MHL', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm nội thất có liên quan khác' ],
                [ 'ma' => 'MPT', 'exchange' =>  'HNX', 'des' => 'Sản xuất phụ kiện và các sản phẩm may mặc khác' ],
                [ 'ma' => 'MSH', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp' ],
                [ 'ma' => 'SAV', 'exchange' => 'HOSE', 'des' => 'Sản xuất tủ bếp và nội thất hộ gia đình' ],
                [ 'ma' => 'SHA', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm nội thất có liên quan khác' ],
                [ 'ma' => 'STK', 'exchange' => 'HOSE', 'des' => 'Sản xuất sợi' ],
                [ 'ma' => 'SVD', 'exchange' => 'HOSE', 'des' => 'Sản xuất sợi' ],
                [ 'ma' => 'TCM', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp' ],
                [ 'ma' => 'TDT', 'exchange' =>  'HNX', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp' ],
                [ 'ma' => 'TET', 'exchange' =>  'HNX', 'des' => 'Sản xuất sản phẩm may mặc dệt kim' ],
                [ 'ma' => 'TNG', 'exchange' =>  'HNX', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp' ],
                [ 'ma' => 'TTF', 'exchange' => 'HOSE', 'des' => 'Sản xuất tủ bếp và nội thất hộ gia đình' ],
                [ 'ma' => 'TVT', 'exchange' => 'HOSE', 'des' => 'Sản xuất sợi, vải thành phẩm' ],
                [ 'ma' => 'X20', 'exchange' =>  'HNX', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp' ],
            ]
        ],
        [
            'name' => 'Sản phẩm cao su',
            'list' => [
                [ 'ma' => 'BRC', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm cao su' ],
                [ 'ma' => 'CSM', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm cao su' ],
                [ 'ma' => 'DRC', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm cao su' ],
                [ 'ma' => 'SRC', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm cao su' ],
            ]
        ],
        [
            'name' => 'SX Nhựa - Hóa chất',
            'list' => [
                [ 'ma' => 'AAA', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'ALT', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'APH', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'BFC', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
                [ 'ma' => 'BMP', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'CPC', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
                [ 'ma' => 'CSV', 'exchange' => 'HOSE', 'des' => 'Sản xuất hóa chất cơ bản' ],
                [ 'ma' => 'DAG', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'DCM', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
                [ 'ma' => 'DGC', 'exchange' => 'HOSE', 'des' => 'Sản xuất hóa chất cơ bản' ],
                [ 'ma' => 'DNP', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'DPC', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'DPM', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
                [ 'ma' => 'DPR', 'exchange' => 'HOSE', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo' ],
                [ 'ma' => 'DTT', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'DVG', 'exchange' =>  'HNX', 'des' => 'Sản xuất sơn và chất kết dính' ],
                [ 'ma' => 'GVR', 'exchange' => 'HOSE', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo' ],
                [ 'ma' => 'HCD', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'HDA', 'exchange' =>  'HNX', 'des' => 'Sản xuất sơn và chất kết dính' ],
                [ 'ma' => 'HII', 'exchange' => 'HOSE', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo' ],
                [ 'ma' => 'HRC', 'exchange' => 'HOSE', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo' ],
                [ 'ma' => 'HVT', 'exchange' =>  'HNX', 'des' => 'Sản xuất hóa chất cơ bản' ],
                [ 'ma' => 'LAS', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
                [ 'ma' => 'LIX', 'exchange' => 'HOSE', 'des' => 'Sản xuất xà phòng, chất tẩy rửa' ],
                [ 'ma' => 'NET', 'exchange' =>  'HNX', 'des' => 'Sản xuất xà phòng, chất tẩy rửa' ],
                [ 'ma' => 'NFC', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
                [ 'ma' => 'NHP', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'NTP', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'PBP', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'PCE', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
                [ 'ma' => 'PGN', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm hóa chất khác' ],
                [ 'ma' => 'PHR', 'exchange' => 'HOSE', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo' ],
                [ 'ma' => 'PLP', 'exchange' => 'HOSE', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo' ],
                [ 'ma' => 'PMB', 'exchange' =>  'HNX', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
                [ 'ma' => 'PMP', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'RDP', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'SDN', 'exchange' =>  'HNX', 'des' => 'Sản xuất sơn và chất kết dính' ],
                [ 'ma' => 'SFG', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
                [ 'ma' => 'SFN', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'TDP', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'TNC', 'exchange' => 'HOSE', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo' ],
                [ 'ma' => 'TPC', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'TPP', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm nhựa' ],
                [ 'ma' => 'TRC', 'exchange' => 'HOSE', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo' ],
                [ 'ma' => 'VAF', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
                [ 'ma' => 'VPS', 'exchange' => 'HOSE', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp' ],
            ]
        ],
        [
            'name' => 'Thực phẩm - Đồ uống',
            'list' => [
                [ 'ma' => 'AGM', 'exchange' => 'HOSE', 'des' => 'Xay sát các loại hạt và hạt có dầu' ],
                [ 'ma' => 'BBC', 'exchange' => 'HOSE', 'des' => 'Sản xuất đường và bánh kẹo' ],
                [ 'ma' => 'BCF', 'exchange' =>  'HNX', 'des' => 'Sản xuất các loại thực phẩm khác' ],
                [ 'ma' => 'BHN', 'exchange' => 'HOSE', 'des' => 'Sản xuất đồ uống' ],
                [ 'ma' => 'BNA', 'exchange' =>  'HNX', 'des' => 'Sản xuất bánh và bánh mì các loại' ],
                [ 'ma' => 'CAN', 'exchange' =>  'HNX', 'des' => 'Bảo quản rau quả và sản xuất thực phẩm chuyên biệt' ],
                [ 'ma' => 'DAT', 'exchange' => 'HOSE', 'des' => 'Sản xuất các loại thực phẩm khác' ],
                [ 'ma' => 'DBC', 'exchange' => 'HOSE', 'des' => 'Giết mổ và chế biến thịt động vật' ],
                [ 'ma' => 'GTN', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm sữa' ],
                [ 'ma' => 'HAD', 'exchange' =>  'HNX', 'des' => 'Sản xuất đồ uống' ],
                [ 'ma' => 'HHC', 'exchange' =>  'HNX', 'des' => 'Sản xuất bánh và bánh mì các loại' ],
                [ 'ma' => 'KDC', 'exchange' => 'HOSE', 'des' => 'Sản xuất bánh và bánh mì các loại' ],
                [ 'ma' => 'KTS', 'exchange' =>  'HNX', 'des' => 'Sản xuất đường và bánh kẹo' ],
                [ 'ma' => 'LAF', 'exchange' => 'HOSE', 'des' => 'Sản xuất các loại thực phẩm khác' ],
                [ 'ma' => 'LSS', 'exchange' => 'HOSE', 'des' => 'Sản xuất đường và bánh kẹo' ],
                [ 'ma' => 'MSN', 'exchange' => 'HOSE', 'des' => 'Sản xuất các loại thực phẩm khác' ],
                [ 'ma' => 'NAF', 'exchange' => 'HOSE', 'des' => 'Bảo quản rau quả và sản xuất thực phẩm chuyên biệt' ],
                [ 'ma' => 'PAN', 'exchange' => 'HOSE', 'des' => 'Sản xuất các loại thực phẩm khác' ],
                [ 'ma' => 'SAB', 'exchange' => 'HOSE', 'des' => 'Sản xuất đồ uống' ],
                [ 'ma' => 'SAF', 'exchange' =>  'HNX', 'des' => 'Sản xuất các loại thực phẩm khác' ],
                [ 'ma' => 'SBT', 'exchange' => 'HOSE', 'des' => 'Sản xuất đường và bánh kẹo' ],
                [ 'ma' => 'SCD', 'exchange' => 'HOSE', 'des' => 'Sản xuất đồ uống' ],
                [ 'ma' => 'SGC', 'exchange' =>  'HNX', 'des' => 'Sản xuất các loại thực phẩm khác' ],
                [ 'ma' => 'SLS', 'exchange' =>  'HNX', 'des' => 'Sản xuất đường và bánh kẹo' ],
                [ 'ma' => 'SMB', 'exchange' => 'HOSE', 'des' => 'Sản xuất đồ uống' ],
                [ 'ma' => 'TAC', 'exchange' => 'HOSE', 'des' => 'Xay sát các loại hạt và hạt có dầu' ],
                [ 'ma' => 'TAR', 'exchange' =>  'HNX', 'des' => 'Xay sát các loại hạt và hạt có dầu' ],
                [ 'ma' => 'TFC', 'exchange' =>  'HNX', 'des' => 'Giết mổ và chế biến thịt động vật' ],
                [ 'ma' => 'THB', 'exchange' =>  'HNX', 'des' => 'Sản xuất đồ uống' ],
                [ 'ma' => 'VCF', 'exchange' => 'HOSE', 'des' => 'Sản xuất đồ uống' ],
                [ 'ma' => 'VDL', 'exchange' =>  'HNX', 'des' => 'Sản xuất đồ uống' ],
                [ 'ma' => 'VHE', 'exchange' =>  'HNX', 'des' => 'Sản xuất các loại thực phẩm khác' ],
                [ 'ma' => 'VNM', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm sữa' ],
                [ 'ma' => 'VTL', 'exchange' =>  'HNX', 'des' => 'Sản xuất đồ uống' ],
            ]
        ],
        [
            'name' => 'Chế biến Thủy sản',
            'list' => [
                [ 'ma' => 'AAM', 'exchange' => 'HOSE', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'ABT', 'exchange' => 'HOSE', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'ACL', 'exchange' => 'HOSE', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'ANV', 'exchange' => 'HOSE', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'BLF', 'exchange' =>  'HNX', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'CMX', 'exchange' => 'HOSE', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'FMC', 'exchange' => 'HOSE', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'IDI', 'exchange' => 'HOSE', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'KHS', 'exchange' =>  'HNX', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'NGC', 'exchange' =>  'HNX', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'SJ1', 'exchange' =>  'HNX', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'TS4', 'exchange' => 'HOSE', 'des' => 'Sơ chế và đóng gói thủy sản' ],
                [ 'ma' => 'VHC', 'exchange' => 'HOSE', 'des' => 'Sơ chế và đóng gói thủy sản' ],
            ]
        ],
        [
            'name' => 'Vật liệu xây dựng',
            'list' => [
                [ 'ma' => 'ACC', 'exchange' => 'HOSE', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'BCC', 'exchange' =>  'HNX', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'BTS', 'exchange' =>  'HNX', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'CLH', 'exchange' =>  'HNX', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'CRC', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'CVT', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'DTL', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua' ],
                [ 'ma' => 'FCM', 'exchange' => 'HOSE', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'GAB', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'GKM', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'GMX', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'HCC', 'exchange' =>  'HNX', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'HLY', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'HOM', 'exchange' =>  'HNX', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'HPG', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua' ],
                [ 'ma' => 'HSG', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua' ],
                [ 'ma' => 'HT1', 'exchange' => 'HOSE', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'HVX', 'exchange' => 'HOSE', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'KKC', 'exchange' =>  'HNX', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua' ],
                [ 'ma' => 'LBM', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'MCC', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'NHC', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'NKG', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua' ],
                [ 'ma' => 'NSH', 'exchange' =>  'HNX', 'des' => 'Sản xuất và chế biến nhôm' ],
                [ 'ma' => 'PDB', 'exchange' =>  'HNX', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'POM', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua' ],
                [ 'ma' => 'S74', 'exchange' =>  'HNX', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'TBX', 'exchange' =>  'HNX', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'TCR', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'TEG', 'exchange' => 'HOSE', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'THG', 'exchange' => 'HOSE', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'TKU', 'exchange' =>  'HNX', 'des' => 'Sản xuất và chế biến nhôm' ],
                [ 'ma' => 'TTC', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'TXM', 'exchange' =>  'HNX', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông' ],
                [ 'ma' => 'VCA', 'exchange' => 'HOSE', 'des' => 'Sản xuất sắt, thép và hợp kim fero' ],
                [ 'ma' => 'VCS', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'VGS', 'exchange' =>  'HNX', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua' ],
                [ 'ma' => 'VHL', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'VIS', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua' ],
                [ 'ma' => 'VIT', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt' ],
                [ 'ma' => 'YBM', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm từ khoáng chất phi kim khác' ],
            ]
        ],
        [
            'name' => 'Tiện ích',
            'list' => [
                [ 'ma' => 'ASP', 'exchange' => 'HOSE', 'des' => 'Phân phối khí đốt thiên nhiên' ],
                [ 'ma' => 'BTP', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'BTW', 'exchange' =>  'HNX', 'des' => 'Hệ thống thủy lợi và cung cấp nước' ],
                [ 'ma' => 'BWE', 'exchange' => 'HOSE', 'des' => 'Hệ thống thủy lợi và cung cấp nước' ],
                [ 'ma' => 'CHP', 'exchange' => 'HOSE', 'des' => 'Truyền tải, kiểm soát và phân phối điện' ],
                [ 'ma' => 'CLW', 'exchange' => 'HOSE', 'des' => 'Hệ thống thủy lợi và cung cấp nước' ],
                [ 'ma' => 'CNG', 'exchange' => 'HOSE', 'des' => 'Phân phối khí đốt thiên nhiên' ],
                [ 'ma' => 'DDG', 'exchange' =>  'HNX', 'des' => 'Cung cấp hơi nước và điều hòa không khí' ],
                [ 'ma' => 'DNC', 'exchange' =>  'HNX', 'des' => 'Truyền tải, kiểm soát và phân phối điện' ],
                [ 'ma' => 'DRL', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'DTK', 'exchange' =>  'HNX', 'des' => 'Phát điện' ],
                [ 'ma' => 'EBA', 'exchange' =>  'HNX', 'des' => 'Phát điện' ],
                [ 'ma' => 'GAS', 'exchange' => 'HOSE', 'des' => 'Phân phối khí đốt thiên nhiên' ],
                [ 'ma' => 'GDW', 'exchange' =>  'HNX', 'des' => 'Hệ thống thủy lợi và cung cấp nước' ],
                [ 'ma' => 'GEG', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'HID', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'HJS', 'exchange' =>  'HNX', 'des' => 'Phát điện' ],
                [ 'ma' => 'IDC', 'exchange' =>  'HNX', 'des' => 'Phát điện' ],
                [ 'ma' => 'KHP', 'exchange' => 'HOSE', 'des' => 'Truyền tải, kiểm soát và phân phối điện' ],
                [ 'ma' => 'NBP', 'exchange' =>  'HNX', 'des' => 'Phát điện' ],
                [ 'ma' => 'NBW', 'exchange' =>  'HNX', 'des' => 'Hệ thống thủy lợi và cung cấp nước' ],
                [ 'ma' => 'NT2', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'NTH', 'exchange' =>  'HNX', 'des' => 'Phát điện' ],
                [ 'ma' => 'PCG', 'exchange' =>  'HNX', 'des' => 'Phân phối khí đốt thiên nhiên' ],
                [ 'ma' => 'PGC', 'exchange' => 'HOSE', 'des' => 'Phân phối khí đốt thiên nhiên' ],
                [ 'ma' => 'PGD', 'exchange' => 'HOSE', 'des' => 'Phân phối khí đốt thiên nhiên' ],
                [ 'ma' => 'PGS', 'exchange' =>  'HNX', 'des' => 'Phân phối khí đốt thiên nhiên' ],
                [ 'ma' => 'PIC', 'exchange' =>  'HNX', 'des' => 'Phát điện' ],
                [ 'ma' => 'POW', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'PPC', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'PVG', 'exchange' =>  'HNX', 'des' => 'Phân phối khí đốt thiên nhiên' ],
                [ 'ma' => 'S4A', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'SBA', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'SEB', 'exchange' =>  'HNX', 'des' => 'Phát điện' ],
                [ 'ma' => 'SHP', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'SII', 'exchange' => 'HOSE', 'des' => 'Hệ thống thủy lợi và cung cấp nước' ],
                [ 'ma' => 'SJD', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'TBC', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'TDM', 'exchange' => 'HOSE', 'des' => 'Hệ thống thủy lợi và cung cấp nước' ],
                [ 'ma' => 'TDW', 'exchange' => 'HOSE', 'des' => 'Hệ thống thủy lợi và cung cấp nước' ],
                [ 'ma' => 'TMP', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'TTA', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
                [ 'ma' => 'TTE', 'exchange' => 'HOSE', 'des' => 'Truyền tải, kiểm soát và phân phối điện' ],
                [ 'ma' => 'UIC', 'exchange' => 'HOSE', 'des' => 'Truyền tải, kiểm soát và phân phối điện' ],
                [ 'ma' => 'VPD', 'exchange' => 'HOSE', 'des' => 'Truyền tải, kiểm soát và phân phối điện' ],
                [ 'ma' => 'VSH', 'exchange' => 'HOSE', 'des' => 'Phát điện' ],
            ]
        ],
        [
            'name' => 'Vận tải - kho bãi',
            'list' => [
                [ 'ma' => 'ASG', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường hàng không' ],
                [ 'ma' => 'BSC', 'exchange' =>  'HNX', 'des' => 'Lưu trữ và kho bãi' ],
                [ 'ma' => 'CAG', 'exchange' =>  'HNX', 'des' => 'Sắp xếp vận tải hàng hóa' ],
                [ 'ma' => 'CDN', 'exchange' =>  'HNX', 'des' => 'Sắp xếp vận tải hàng hóa' ],
                [ 'ma' => 'CLL', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'DL1', 'exchange' =>  'HNX', 'des' => 'Vận tải trung chuyển và vận tải hành khách bằng đường bộ khác' ],
                [ 'ma' => 'DS3', 'exchange' =>  'HNX', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'DVP', 'exchange' => 'HOSE', 'des' => 'Sắp xếp vận tải hàng hóa' ],
                [ 'ma' => 'DXP', 'exchange' =>  'HNX', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'GIC', 'exchange' =>  'HNX', 'des' => 'Các hoạt động hỗ trợ vận tải khác' ],
                [ 'ma' => 'GMD', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'GSP', 'exchange' => 'HOSE', 'des' => 'Vận tải đường thủy nội địa' ],
                [ 'ma' => 'HAH', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'HCT', 'exchange' =>  'HNX', 'des' => 'Vận tải đường bộ' ],
                [ 'ma' => 'HHG', 'exchange' =>  'HNX', 'des' => 'Vận tải đường bộ' ],
                [ 'ma' => 'HMH', 'exchange' =>  'HNX', 'des' => 'Sắp xếp vận tải hàng hóa' ],
                [ 'ma' => 'HTV', 'exchange' => 'HOSE', 'des' => 'Vận tải đường thủy nội địa' ],
                [ 'ma' => 'HVN', 'exchange' => 'HOSE', 'des' => 'Vận tải hàng không đã được xếp lịch' ],
                [ 'ma' => 'ILB', 'exchange' => 'HOSE', 'des' => 'Lưu trữ và kho bãi' ],
                [ 'ma' => 'MAC', 'exchange' =>  'HNX', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'MAS', 'exchange' =>  'HNX', 'des' => 'Hoạt động hỗ trợ vận tải đường hàng không' ],
                [ 'ma' => 'MHC', 'exchange' => 'HOSE', 'des' => 'Vận tải đường thủy nội địa' ],
                [ 'ma' => 'NAP', 'exchange' =>  'HNX', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'NCT', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường hàng không' ],
                [ 'ma' => 'PDN', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'PGT', 'exchange' =>  'HNX', 'des' => 'Dịch vụ taxi' ],
                [ 'ma' => 'PHP', 'exchange' =>  'HNX', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'PJC', 'exchange' =>  'HNX', 'des' => 'Vận tải đường bộ chuyên biệt' ],
                [ 'ma' => 'PJT', 'exchange' => 'HOSE', 'des' => 'Vận tải đường biển, ven biển, hồ lớn' ],
                [ 'ma' => 'PRC', 'exchange' =>  'HNX', 'des' => 'Vận tải đường bộ' ],
                [ 'ma' => 'PTS', 'exchange' =>  'HNX', 'des' => 'Vận tải đường thủy nội địa' ],
                [ 'ma' => 'PVT', 'exchange' => 'HOSE', 'des' => 'Vận tải đường biển, ven biển, hồ lớn' ],
                [ 'ma' => 'SCS', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường hàng không' ],
                [ 'ma' => 'SFI', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'SGN', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường hàng không' ],
                [ 'ma' => 'SKG', 'exchange' => 'HOSE', 'des' => 'Vận tải đường thủy nội địa' ],
                [ 'ma' => 'STG', 'exchange' => 'HOSE', 'des' => 'Lưu trữ và kho bãi' ],
                [ 'ma' => 'TCL', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'TCO', 'exchange' => 'HOSE', 'des' => 'Sắp xếp vận tải hàng hóa' ],
                [ 'ma' => 'TCT', 'exchange' => 'HOSE', 'des' => 'Vận chuyển du lịch khác' ],
                [ 'ma' => 'TJC', 'exchange' =>  'HNX', 'des' => 'Vận tải đường biển, ven biển, hồ lớn' ],
                [ 'ma' => 'TMS', 'exchange' => 'HOSE', 'des' => 'Sắp xếp vận tải hàng hóa' ],
                [ 'ma' => 'TTZ', 'exchange' =>  'HNX', 'des' => 'Vận tải đường bộ' ],
                [ 'ma' => 'VGP', 'exchange' =>  'HNX', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'VIP', 'exchange' => 'HOSE', 'des' => 'Vận tải đường thủy nội địa' ],
                [ 'ma' => 'VJC', 'exchange' => 'HOSE', 'des' => 'Vận tải hàng không đã được xếp lịch' ],
                [ 'ma' => 'VMS', 'exchange' =>  'HNX', 'des' => 'Các hoạt động hỗ trợ vận tải khác' ],
                [ 'ma' => 'VNF', 'exchange' =>  'HNX', 'des' => 'Sắp xếp vận tải hàng hóa' ],
                [ 'ma' => 'VNL', 'exchange' => 'HOSE', 'des' => 'Sắp xếp vận tải hàng hóa' ],
                [ 'ma' => 'VNS', 'exchange' => 'HOSE', 'des' => 'Dịch vụ taxi' ],
                [ 'ma' => 'VNT', 'exchange' =>  'HNX', 'des' => 'Sắp xếp vận tải hàng hóa' ],
                [ 'ma' => 'VOS', 'exchange' => 'HOSE', 'des' => 'Vận tải đường biển, ven biển, hồ lớn' ],
                [ 'ma' => 'VSA', 'exchange' =>  'HNX', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'VSC', 'exchange' => 'HOSE', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy' ],
                [ 'ma' => 'VSM', 'exchange' =>  'HNX', 'des' => 'Vận tải đường bộ' ],
                [ 'ma' => 'VTO', 'exchange' => 'HOSE', 'des' => 'Vận tải đường biển, ven biển, hồ lớn' ],
                [ 'ma' => 'WCS', 'exchange' =>  'HNX', 'des' => 'Hoạt động hỗ trợ vận tải đường bộ' ]
            ]
        ],
        [
            'name' => 'Xây dựng',
            'list' => [
                [ 'ma' => 'AME', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'BCG', 'exchange' => 'HOSE', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'C47', 'exchange' => 'HOSE', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'C69', 'exchange' =>  'HNX', 'des' => 'Xây dựng công trình khác' ],
                [ 'ma' => 'C92', 'exchange' =>  'HNX', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'CEE', 'exchange' => 'HOSE', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'CII', 'exchange' => 'HOSE', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'CLG', 'exchange' => 'HOSE', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'CMS', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'CSC', 'exchange' =>  'HNX', 'des' => 'Xây dựng công trình khác' ],
                [ 'ma' => 'CTD', 'exchange' => 'HOSE', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'CTI', 'exchange' => 'HOSE', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'CTX', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'CX8', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'DC2', 'exchange' =>  'HNX', 'des' => 'Nhà thầu về nền móng, cấu trúc và bề mặt ngoài' ],
                [ 'ma' => 'DC4', 'exchange' => 'HOSE', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'DIH', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'DPG', 'exchange' => 'HOSE', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'DTD', 'exchange' =>  'HNX', 'des' => 'Xây dựng công trình khác' ],
                [ 'ma' => 'FCN', 'exchange' => 'HOSE', 'des' => 'Nhà thầu về nền móng, cấu trúc và bề mặt ngoài' ],
                [ 'ma' => 'HAS', 'exchange' => 'HOSE', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'HBC', 'exchange' => 'HOSE', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'HTI', 'exchange' => 'HOSE', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'HTN', 'exchange' => 'HOSE', 'des' => 'Nhà thầu hoàn thiện xây dựng' ],
                [ 'ma' => 'HU3', 'exchange' => 'HOSE', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'HUB', 'exchange' => 'HOSE', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'HVH', 'exchange' => 'HOSE', 'des' => 'Nhà thầu chuyên môn khác' ],
                [ 'ma' => 'IDJ', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'KTT', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'L10', 'exchange' => 'HOSE', 'des' => 'Nhà thầu về nền móng, cấu trúc và bề mặt ngoài' ],
                [ 'ma' => 'L18', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'L35', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'L40', 'exchange' =>  'HNX', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'L43', 'exchange' =>  'HNX', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'L61', 'exchange' =>  'HNX', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'L62', 'exchange' =>  'HNX', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'LCD', 'exchange' =>  'HNX', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'LCG', 'exchange' => 'HOSE', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'LCS', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'LEC', 'exchange' => 'HOSE', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'LGC', 'exchange' => 'HOSE', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'LHC', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'LIG', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'LM7', 'exchange' =>  'HNX', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'LM8', 'exchange' => 'HOSE', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'LO5', 'exchange' =>  'HNX', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'LUT', 'exchange' =>  'HNX', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'MCO', 'exchange' =>  'HNX', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'MST', 'exchange' =>  'HNX', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'NDX', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'PC1', 'exchange' => 'HOSE', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'PEN', 'exchange' =>  'HNX', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'PHC', 'exchange' => 'HOSE', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'PPS', 'exchange' =>  'HNX', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'PTC', 'exchange' => 'HOSE', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'PTD', 'exchange' =>  'HNX', 'des' => 'Xây dựng công trình khác' ],
                [ 'ma' => 'PXS', 'exchange' => 'HOSE', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'PXT', 'exchange' => 'HOSE', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'QTC', 'exchange' =>  'HNX', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'REE', 'exchange' => 'HOSE', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'ROS', 'exchange' => 'HOSE', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'S55', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'S99', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'SC5', 'exchange' => 'HOSE', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'SCI', 'exchange' =>  'HNX', 'des' => 'Xây dựng công trình khác' ],
                [ 'ma' => 'SD2', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'SD4', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'SD5', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'SD6', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'SD9', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'SDT', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'SJE', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'SRF', 'exchange' => 'HOSE', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'TA9', 'exchange' =>  'HNX', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'TCD', 'exchange' => 'HOSE', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'TGG', 'exchange' => 'HOSE', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'THD', 'exchange' =>  'HNX', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'TKC', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'TST', 'exchange' =>  'HNX', 'des' => 'Nhà thầu thiết bị xây dựng' ],
                [ 'ma' => 'TTL', 'exchange' =>  'HNX', 'des' => 'Xây dựng cầu đường, đường cao tốc' ],
                [ 'ma' => 'UDC', 'exchange' => 'HOSE', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'V12', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'V21', 'exchange' =>  'HNX', 'des' => 'Xây dựng công trình khác' ],
                [ 'ma' => 'VC1', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'VC2', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'VC6', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'VC9', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'VCC', 'exchange' =>  'HNX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc' ],
                [ 'ma' => 'VCG', 'exchange' => 'HOSE', 'des' => 'Nhà thầu về nền móng, cấu trúc và bề mặt ngoài' ],
                [ 'ma' => 'VE1', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'VE2', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'VE3', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'VE4', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'VE8', 'exchange' =>  'HNX', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'VMC', 'exchange' =>  'HNX', 'des' => 'Nhà thầu về nền móng, cấu trúc và bề mặt ngoài' ],
                [ 'ma' => 'VMI', 'exchange' =>  'HNX', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác' ],
                [ 'ma' => 'VNE', 'exchange' => 'HOSE', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'VSI', 'exchange' => 'HOSE', 'des' => 'Xây dựng hệ thống tiện ích' ],
                [ 'ma' => 'VXB', 'exchange' =>  'HNX', 'des' => 'Xây dựng công trình khác' ],
            ]
        ],
        [
            'name' => 'Dịch vụ lưu trú, ăn uống, giải trí',
            'list' => [
                [ 'ma' => 'ATS', 'exchange' =>  'HNX', 'des' => 'Nhà hàng đầy đủ dịch vụ' ],
                [ 'ma' => 'DAH', 'exchange' => 'HOSE', 'des' => 'Chỗ ở cho khách du lịch' ],
                [ 'ma' => 'DSN', 'exchange' => 'HOSE', 'des' => 'Khu vui chơi giải trí' ],
                [ 'ma' => 'HOT', 'exchange' => 'HOSE', 'des' => 'Chỗ ở cho khách du lịch' ],
                [ 'ma' => 'NVT', 'exchange' => 'HOSE', 'des' => 'Chỗ ở cho khách du lịch' ],
                [ 'ma' => 'OCH', 'exchange' =>  'HNX', 'des' => 'Chỗ ở cho khách du lịch' ],
                [ 'ma' => 'PDC', 'exchange' =>  'HNX', 'des' => 'Chỗ ở cho khách du lịch' ],
                [ 'ma' => 'RIC', 'exchange' => 'HOSE', 'des' => 'Cá cược và đánh bạc' ],
                [ 'ma' => 'SDA', 'exchange' =>  'HNX', 'des' => 'Dịch vụ việc làm' ],
                [ 'ma' => 'SGH', 'exchange' =>  'HNX', 'des' => 'Chỗ ở cho khách du lịch' ],
                [ 'ma' => 'TTT', 'exchange' =>  'HNX', 'des' => 'Các dịch vụ hỗ trợ khác' ],
                [ 'ma' => 'VCM', 'exchange' =>  'HNX', 'des' => 'Dịch vụ việc làm' ],
                [ 'ma' => 'VNG', 'exchange' => 'HOSE', 'des' => 'Chỗ ở cho khách du lịch' ],
            ]
        ],
        [
            'name' => 'SX Phụ trợ',
            'list' => [
                [ 'ma' => 'APP', 'exchange' =>  'HNX', 'des' => 'Sản xuất sản phẩm xăng dầu và than đá khác' ],
                [ 'ma' => 'BBS', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
                [ 'ma' => 'BKG', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm gỗ khác' ],
                [ 'ma' => 'BPC', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
                [ 'ma' => 'BXH', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
                [ 'ma' => 'CAP', 'exchange' =>  'HNX', 'des' => 'Nhà máy sản xuất bột giấy, giấy và giấy bìa' ],
                [ 'ma' => 'CET', 'exchange' =>  'HNX', 'des' => 'Sản xuất khác' ],
                [ 'ma' => 'DHC', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
                [ 'ma' => 'DLG', 'exchange' => 'HOSE', 'des' => 'Sản xuất linh kiện bán dẫn và các linh kiện điện tử khác' ],
                [ 'ma' => 'DNM', 'exchange' =>  'HNX', 'des' => 'Sản xuất dụng cụ và thiết bị y tế' ],
                [ 'ma' => 'GTA', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm gỗ khác' ],
                [ 'ma' => 'HAP', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
                [ 'ma' => 'HHP', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
                [ 'ma' => 'HTP', 'exchange' =>  'HNX', 'des' => 'In ấn' ],
                [ 'ma' => 'INN', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
                [ 'ma' => 'ITQ', 'exchange' =>  'HNX', 'des' => 'Sản xuất sản phẩm kim loại tổng hợp khác' ],
                [ 'ma' => 'KVC', 'exchange' =>  'HNX', 'des' => 'Sản xuất sản phẩm kim loại tổng hợp khác' ],
                [ 'ma' => 'MCP', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm kim loại tổng hợp khác' ],
                [ 'ma' => 'PLC', 'exchange' =>  'HNX', 'des' => 'Sản xuất nhựa đường, vật liệu lợp mái và chất bão hòa' ],
                [ 'ma' => 'PMS', 'exchange' =>  'HNX', 'des' => 'Sản xuất lò hơi, thùng chứa và container vận chuyển' ],
                [ 'ma' => 'PNJ', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm kim loại tổng hợp khác' ],
                [ 'ma' => 'SBV', 'exchange' => 'HOSE', 'des' => 'Sản xuất khác' ],
                [ 'ma' => 'SDG', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
                [ 'ma' => 'SHI', 'exchange' => 'HOSE', 'des' => 'Sản xuất sản phẩm kim loại tổng hợp khác' ],
                [ 'ma' => 'SMT', 'exchange' =>  'HNX', 'des' => 'Sản xuất thiết bị truyền thông từ tính và quang học' ],
                [ 'ma' => 'SSM', 'exchange' =>  'HNX', 'des' => 'Sản xuất kiến trúc và kết cấu kim loại' ],
                [ 'ma' => 'STP', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
                [ 'ma' => 'SVI', 'exchange' => 'HOSE', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
                [ 'ma' => 'SVT', 'exchange' => 'HOSE', 'des' => 'Sản xuất phụ tùng xe cơ giới' ],
                [ 'ma' => 'TLD', 'exchange' => 'HOSE', 'des' => 'Sản xuất gỗ ốp, ván ép và các sản phẩm gỗ lắp ghép' ],
                [ 'ma' => 'TLG', 'exchange' => 'HOSE', 'des' => 'Sản xuất khác' ],
                [ 'ma' => 'TMT', 'exchange' => 'HOSE', 'des' => 'Sản xuất xe cơ giới' ],
                [ 'ma' => 'VBC', 'exchange' =>  'HNX', 'des' => 'Sản xuất các sản phẩm từ giấy' ],
            ]
        ],
        [
            'name' => 'Thiết bị điện',
            'list' => [
                [ 'ma' => 'CAV', 'exchange' => 'HOSE', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác' ],
                [ 'ma' => 'DHP', 'exchange' =>  'HNX', 'des' => 'Sản xuất đồ điện gia dụng' ],
                [ 'ma' => 'DQC', 'exchange' => 'HOSE', 'des' => 'Sản xuất thiết bị điện chiếu sáng' ],
                [ 'ma' => 'EMC', 'exchange' => 'HOSE', 'des' => 'Sản xuất thiết bị điện' ],
                [ 'ma' => 'GEX', 'exchange' => 'HOSE', 'des' => 'Sản xuất thiết bị điện' ],
                [ 'ma' => 'KSD', 'exchange' =>  'HNX', 'des' => 'Sản xuất đồ điện gia dụng' ],
                [ 'ma' => 'MBG', 'exchange' =>  'HNX', 'des' => 'Sản xuất thiết bị điện chiếu sáng' ],
                [ 'ma' => 'PAC', 'exchange' => 'HOSE', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác' ],
                [ 'ma' => 'PHN', 'exchange' =>  'HNX', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác' ],
                [ 'ma' => 'POT', 'exchange' =>  'HNX', 'des' => 'Sản xuất thiết bị truyền thông' ],
                [ 'ma' => 'RAL', 'exchange' => 'HOSE', 'des' => 'Sản xuất thiết bị điện chiếu sáng' ],
                [ 'ma' => 'SAM', 'exchange' => 'HOSE', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác' ],
                [ 'ma' => 'TSB', 'exchange' =>  'HNX', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác' ],
                [ 'ma' => 'TYA', 'exchange' => 'HOSE', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác' ],
                [ 'ma' => 'VTB', 'exchange' => 'HOSE', 'des' => 'Sản xuất thiết bị truyền thông' ],
                [ 'ma' => 'VTH', 'exchange' =>  'HNX', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác' ],
            ]
        ],
        [
            'name' => 'Dịch vụ tư vấn, hỗ trợ',
            'list' => [
                [ 'ma' => 'IBC', 'exchange' => 'HOSE', 'des' => 'Dịch vụ tư vấn quản lý' ],
                [ 'ma' => 'INC', 'exchange' =>  'HNX', 'des' => 'Dịch vụ tư vấn xây dựng' ],
                [ 'ma' => 'KPF', 'exchange' => 'HOSE', 'des' => 'Dịch vụ tư vấn xây dựng' ],
                [ 'ma' => 'PPE', 'exchange' =>  'HNX', 'des' => 'Dịch vụ tư vấn xây dựng' ],
                [ 'ma' => 'SDA', 'exchange' =>  'HNX', 'des' => 'Dịch vụ việc làm' ],
                [ 'ma' => 'SDC', 'exchange' =>  'HNX', 'des' => 'Dịch vụ thiết kế công nghiệp' ],
                [ 'ma' => 'TV2', 'exchange' => 'HOSE', 'des' => 'Dịch vụ tư vấn xây dựng' ],
                [ 'ma' => 'TV3', 'exchange' =>  'HNX', 'des' => 'Dịch vụ tư vấn xây dựng' ],
                [ 'ma' => 'TV4', 'exchange' =>  'HNX', 'des' => 'Dịch vụ tư vấn xây dựng' ],
                [ 'ma' => 'VAT', 'exchange' =>  'HNX', 'des' => 'Dịch vụ tư vấn xây dựng' ],
                [ 'ma' => 'VCM', 'exchange' =>  'HNX', 'des' => 'Dịch vụ việc làm' ],
                [ 'ma' => 'VLA', 'exchange' =>  'HNX', 'des' => 'Dịch vụ lập trình máy tính' ],
                [ 'ma' => 'VNC', 'exchange' =>  'HNX', 'des' => 'Các dịch vụ chuyên môn, khoa học và kỹ thuật khác' ],
            ]
        ],
        [
            'name' => 'Tài chính khác',
            'list' => [
                [ 'ma' => 'OGC', 'exchange' => 'HOSE', 'des' => 'Các hoạt động đầu tư tài chính khác' ],
                [ 'ma' => 'TVC', 'exchange' =>  'HNX', 'des' => 'Các hoạt động đầu tư tài chính khác' ],
            ]
        ]
    ];

    public function getGroupNames()
    {
        return array_column(self::GROUPS_DATA, 'name');
    }

    /**
     * @param string $code
     * @return array|null
     */
    public function findCodeDetail(string $code)
    {
        foreach (self::GROUPS_DATA as $group) {
            foreach ($group['list'] as $detail) {
                if ($detail['ma'] == $code) {
                    $detail['groupName'] = $group['name'];
                    return $detail;
                }
            }
        }
    }
}