<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Codes extends Seeder
{
    public function run()
    {
        $rows = [
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'AAT', 'des' => 'Bán buôn quần áo, vải và vật tư liên quan', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'ABS', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'ACB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 16, 'exchange' => 'HOSE', 'name' => 'ACL', 'des' => 'Sơ chế và đóng gói thủy sản', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HOSE', 'name' => 'ADS', 'des' => 'Sản xuất sợi, vải thành phẩm', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'AGG', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'AGM', 'des' => 'Xay sát các loại hạt và hạt có dầu', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'AGR', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HOSE', 'name' => 'AMD', 'des' => 'Kinh doanh vật liệu xây dựng và vật tư liên quan', 'active' => 1],
            [ 'groupId' => 16, 'exchange' => 'HOSE', 'name' => 'ANV', 'des' => 'Sơ chế và đóng gói thủy sản', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'APG', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 10, 'exchange' => 'HOSE', 'name' => 'ASM', 'des' => 'Nuôi trồng thủy sản', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'ASP', 'des' => 'Phân phối khí đốt thiên nhiên', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'BCE', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'BCG', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'BCM', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 2, 'exchange' => 'HOSE', 'name' => 'BIC', 'des' => 'Hãng bảo hiểm', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'BID', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'BKG', 'des' => 'Sản xuất các sản phẩm gỗ khác', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HOSE', 'name' => 'BMC', 'des' => 'Khai thác quặng kim loại', 'active' => 1],
            [ 'groupId' => 2, 'exchange' => 'HOSE', 'name' => 'BMI', 'des' => 'Hãng bảo hiểm', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'BTP', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HOSE', 'name' => 'BTT', 'des' => 'Cửa hàng tổng hợp', 'active' => 1],
            [ 'groupId' => 2, 'exchange' => 'HOSE', 'name' => 'BVH', 'des' => 'Hãng bảo hiểm', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'BWE', 'des' => 'Hệ thống thủy lợi và cung cấp nước', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HOSE', 'name' => 'C32', 'des' => 'Khai thác đá và khoáng sản phi kim', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'C47', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'CCL', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'CDC', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'CEE', 'des' => 'Xây dựng cầu đường, đường cao tốc', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'CIG', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'CII', 'des' => 'Xây dựng cầu đường, đường cao tốc', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'CKG', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'CLW', 'des' => 'Hệ thống thủy lợi và cung cấp nước', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HOSE', 'name' => 'CMG', 'des' => 'Các dịch vụ thông tin khác', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HOSE', 'name' => 'CMV', 'des' => 'Cửa hàng tổng hợp', 'active' => 1],
            [ 'groupId' => 16, 'exchange' => 'HOSE', 'name' => 'CMX', 'des' => 'Sơ chế và đóng gói thủy sản', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'CNG', 'des' => 'Phân phối khí đốt thiên nhiên', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'CRE', 'des' => 'Đại lý và môi giới bất động sản', 'active' => 1],
            [ 'groupId' => 13, 'exchange' => 'HOSE', 'name' => 'CSM', 'des' => 'Sản xuất các sản phẩm cao su', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'CTD', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HOSE', 'name' => 'CTF', 'des' => 'Cửa hàng phụ tùng xe hơi, phụ kiện và săm lốp', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'CTG', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'CTI', 'des' => 'Xây dựng cầu đường, đường cao tốc', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'CTS', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'D2D', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 21, 'exchange' => 'HOSE', 'name' => 'DAH', 'des' => 'Chỗ ở cho khách du lịch', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'DAT', 'des' => 'Sản xuất các loại thực phẩm khác', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'DBC', 'des' => 'Giết mổ và chế biến thịt động vật', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'DBT', 'des' => 'Bán buôn dược phẩm và tạp hóa dược', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'DC4', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'DGW', 'des' => 'Bán buôn các mặt hàng điện, điện tử', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HOSE', 'name' => 'DHA', 'des' => 'Khai thác đá và khoáng sản phi kim', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'DHC', 'des' => 'Sản xuất các sản phẩm từ giấy', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HOSE', 'name' => 'DHM', 'des' => 'Khai thác quặng kim loại', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'DIG', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'DLG', 'des' => 'Sản xuất linh kiện bán dẫn và các linh kiện điện tử khác', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'DPG', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 23, 'exchange' => 'HOSE', 'name' => 'DQC', 'des' => 'Sản xuất thiết bị điện chiếu sáng', 'active' => 1],
            [ 'groupId' => 13, 'exchange' => 'HOSE', 'name' => 'DRC', 'des' => 'Sản xuất các sản phẩm cao su', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'DRH', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'DXG', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'EIB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HOSE', 'name' => 'ELC', 'des' => 'Các loại hình viễn thông khác', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HOSE', 'name' => 'EVE', 'des' => 'Sản xuất phụ kiện và các sản phẩm may mặc khác', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'EVG', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'FCN', 'des' => 'Nhà thầu về nền móng, cấu trúc và bề mặt ngoài', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'FIR', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'FLC', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 16, 'exchange' => 'HOSE', 'name' => 'FMC', 'des' => 'Sơ chế và đóng gói thủy sản', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HOSE', 'name' => 'FPT', 'des' => 'Sản xuất phần mềm', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HOSE', 'name' => 'FRT', 'des' => 'Cửa hàng máy tính và phần mềm', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HOSE', 'name' => 'FTM', 'des' => 'Sản xuất sợi', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'FTS', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'GAS', 'des' => 'Phân phối khí đốt thiên nhiên', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'GEG', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 23, 'exchange' => 'HOSE', 'name' => 'GEX', 'des' => 'Sản xuất thiết bị điện', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HOSE', 'name' => 'GIL', 'des' => 'Sản xuất phụ kiện và các sản phẩm may mặc khác', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HOSE', 'name' => 'GMC', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'GMD', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'GSP', 'des' => 'Vận tải đường thủy nội địa', 'active' => 1],
            [ 'groupId' => 10, 'exchange' => 'HOSE', 'name' => 'HAG', 'des' => 'Trồng trọt cây có hạt và các loại trái cây', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'HAH', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'HAI', 'des' => 'Bán buôn hóa chất và các sản phẩm liên quan', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'HAP', 'des' => 'Sản xuất các sản phẩm từ giấy', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'HAR', 'des' => 'Đại lý và môi giới bất động sản', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HOSE', 'name' => 'HAX', 'des' => 'Bán lẻ xe hơi', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'HBC', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'HCM', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'HDB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'HDC', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'HDG', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'HHP', 'des' => 'Sản xuất các sản phẩm từ giấy', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'HHS', 'des' => 'Bán buôn xe cơ giới và phụ tùng xe cơ giới', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'HID', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'HMC', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)', 'active' => 1],
            [ 'groupId' => 10, 'exchange' => 'HOSE', 'name' => 'HNG', 'des' => 'Trồng trọt các loại cây khác', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'HPX', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'HQC', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 10, 'exchange' => 'HOSE', 'name' => 'HSL', 'des' => 'Trồng trọt cây lương thực và các loại hạt có dầu', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'HTI', 'des' => 'Xây dựng cầu đường, đường cao tốc', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'HTN', 'des' => 'Nhà thầu hoàn thiện xây dựng', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'HVH', 'des' => 'Nhà thầu chuyên môn khác', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'HVN', 'des' => 'Vận tải hàng không đã được xếp lịch', 'active' => 1],
            [ 'groupId' => 24, 'exchange' => 'HOSE', 'name' => 'IBC', 'des' => 'Dịch vụ tư vấn quản lý', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HOSE', 'name' => 'ICT', 'des' => 'Các loại hình viễn thông khác', 'active' => 1],
            [ 'groupId' => 16, 'exchange' => 'HOSE', 'name' => 'IDI', 'des' => 'Sơ chế và đóng gói thủy sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'IJC', 'des' => 'Phát triển Hạ tầng Kỹ thuật. huyển Dự án Quốc lộ 13 trực thuộc Công ty Đầu tư và Phát triển Công nghiệp thành công ty cổ phần Phát triển Hạ tầng Kỹ thuật.', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'ITA', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'ITC', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HOSE', 'name' => 'ITD', 'des' => 'Các loại hình viễn thông khác', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'JVC', 'des' => 'Bán buôn các thiết bị, vật tư chuyên môn và thương mại', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'KBC', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'KDC', 'des' => 'Sản xuất bánh và bánh mì các loại', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'KDH', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'KHP', 'des' => 'Truyền tải, kiểm soát và phân phối điện', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HOSE', 'name' => 'KMR', 'des' => 'Sản xuất các sản phẩm dệt dùng trong nhà', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'KOS', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HOSE', 'name' => 'KSB', 'des' => 'Khai thác đá và khoáng sản phi kim', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'LCG', 'des' => 'Xây dựng cầu đường, đường cao tốc', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HOSE', 'name' => 'LCM', 'des' => 'Khai thác quặng kim loại', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'LDG', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'LGL', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'LHG', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'LPB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'LSS', 'des' => 'Sản xuất đường và bánh kẹo', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'MBB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 11, 'exchange' => 'HOSE', 'name' => 'MCG', 'des' => 'Sản xuất thiết bị nông nghiệp, xây dựng và khai khoáng', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'MHC', 'des' => 'Vận tải đường thủy nội địa', 'active' => 1],
            [ 'groupId' => 2, 'exchange' => 'HOSE', 'name' => 'MIG', 'des' => 'Hãng bảo hiểm', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'MSB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HOSE', 'name' => 'MSH', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'MSN', 'des' => 'Sản xuất các loại thực phẩm khác', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HOSE', 'name' => 'MWG', 'des' => 'Cửa hàng máy tính và phần mềm', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'NAF', 'des' => 'Bảo quản rau quả và sản xuất thực phẩm chuyên biệt', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'NBB', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'NHA', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 11, 'exchange' => 'HOSE', 'name' => 'NHH', 'des' => 'Sản xuất thiết bị, máy móc công nghiệp', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'NLG', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HOSE', 'name' => 'NNC', 'des' => 'Khai thác đá và khoáng sản phi kim', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'NT2', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'NTL', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'NVL', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 21, 'exchange' => 'HOSE', 'name' => 'NVT', 'des' => 'Chỗ ở cho khách du lịch', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'OCB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 25, 'exchange' => 'HOSE', 'name' => 'OGC', 'des' => 'Các hoạt động đầu tư tài chính khác', 'active' => 1],
            [ 'groupId' => 23, 'exchange' => 'HOSE', 'name' => 'PAC', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'PC1', 'des' => 'Xây dựng hệ thống tiện ích', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'PDN', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'PDR', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'PET', 'des' => 'Bán buôn các mặt hàng điện, điện tử', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'PGC', 'des' => 'Phân phối khí đốt thiên nhiên', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'PHC', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'PLX', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'PMG', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HOSE', 'name' => 'PNC', 'des' => 'Cửa hàng dụng cụ, văn phòng phẩm và quà tặng', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'PNJ', 'des' => 'Sản xuất sản phẩm kim loại tổng hợp khác', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'POW', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'PPC', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'PSH', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'PTB', 'des' => 'Bán buôn xe cơ giới và phụ tùng xe cơ giới', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'PTC', 'des' => 'Nhà thầu thiết bị xây dựng', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'PTL', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HOSE', 'name' => 'PVD', 'des' => 'Khoan giếng dầu và khí đốt', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'PVT', 'des' => 'Vận tải đường biển, ven biển, hồ lớn', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'PXI', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'QCG', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 23, 'exchange' => 'HOSE', 'name' => 'RAL', 'des' => 'Sản xuất thiết bị điện chiếu sáng', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'REE', 'des' => 'Nhà thầu thiết bị xây dựng', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'ROS', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'SAB', 'des' => 'Sản xuất đồ uống', 'active' => 1],
            [ 'groupId' => 23, 'exchange' => 'HOSE', 'name' => 'SAM', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'SBA', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'SBT', 'des' => 'Sản xuất đường và bánh kẹo', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'SBV', 'des' => 'Sản xuất khác', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'SCR', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'SCS', 'des' => 'Hoạt động hỗ trợ vận tải đường hàng không', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'SGR', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'SGT', 'des' => 'Bán buôn các thiết bị, vật tư chuyên môn và thương mại', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'SHI', 'des' => 'Sản xuất sản phẩm kim loại tổng hợp khác', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'SHP', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'SJD', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 10, 'exchange' => 'HOSE', 'name' => 'SJF', 'des' => 'Trồng trọt các loại cây khác', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'SJS', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'SKG', 'des' => 'Vận tải đường thủy nội địa', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'SMC', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'SRF', 'des' => 'Nhà thầu thiết bị xây dựng', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'SSB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'SSI', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'STB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'STG', 'des' => 'Lưu trữ và kho bãi', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HOSE', 'name' => 'SVD', 'des' => 'Sản xuất sợi', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'SVT', 'des' => 'Sản xuất phụ tùng xe cơ giới', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'SZC', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'TCB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'TCD', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'TCH', 'des' => 'Bán buôn xe cơ giới và phụ tùng xe cơ giới', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'TCL', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HOSE', 'name' => 'TCM', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'TCO', 'des' => 'Sắp xếp vận tải hàng hóa', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'TDC', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'TDG', 'des' => 'Bán buôn dầu và các sản phẩm dầu khí', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'TDH', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'TDM', 'des' => 'Hệ thống thủy lợi và cung cấp nước', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'TGG', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'TIP', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'TLD', 'des' => 'Sản xuất gỗ ốp, ván ép và các sản phẩm gỗ lắp ghép', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'TLG', 'des' => 'Sản xuất khác', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'TLH', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HOSE', 'name' => 'TMT', 'des' => 'Sản xuất xe cơ giới', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'TNA', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'TNI', 'des' => 'Bán buôn máy móc, thiết bị và vật tư', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HOSE', 'name' => 'TNT', 'des' => 'Khai thác quặng kim loại', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'TPB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 16, 'exchange' => 'HOSE', 'name' => 'TS4', 'des' => 'Sơ chế và đóng gói thủy sản', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'TSC', 'des' => 'Bán buôn hóa chất và các sản phẩm liên quan', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'TTA', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'TTB', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HOSE', 'name' => 'TTF', 'des' => 'Sản xuất tủ bếp và nội thất hộ gia đình', 'active' => 1],
            [ 'groupId' => 24, 'exchange' => 'HOSE', 'name' => 'TV2', 'des' => 'Dịch vụ tư vấn xây dựng', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'TVS', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 23, 'exchange' => 'HOSE', 'name' => 'TYA', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'UDC', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'VCB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'VCF', 'des' => 'Sản xuất đồ uống', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'VCG', 'des' => 'Nhà thầu về nền móng, cấu trúc và bề mặt ngoài', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'VCI', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'VDS', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HOSE', 'name' => 'VGC', 'des' => 'Kinh doanh vật liệu xây dựng và vật tư liên quan', 'active' => 1],
            [ 'groupId' => 16, 'exchange' => 'HOSE', 'name' => 'VHC', 'des' => 'Sơ chế và đóng gói thủy sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'VHM', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'VIB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'VIC', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'VID', 'des' => 'Bán buôn giấy và các sản phẩm từ giấy', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'VIP', 'des' => 'Vận tải đường thủy nội địa', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'VIX', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'VJC', 'des' => 'Vận tải hàng không đã được xếp lịch', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HOSE', 'name' => 'VNE', 'des' => 'Xây dựng hệ thống tiện ích', 'active' => 1],
            [ 'groupId' => 21, 'exchange' => 'HOSE', 'name' => 'VNG', 'des' => 'Chỗ ở cho khách du lịch', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'VNM', 'des' => 'Sản xuất sản phẩm sữa', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'VNS', 'des' => 'Dịch vụ taxi', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'VOS', 'des' => 'Vận tải đường biển, ven biển, hồ lớn', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HOSE', 'name' => 'VPB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'VPD', 'des' => 'Truyền tải, kiểm soát và phân phối điện', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'VPG', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'VPH', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'VPI', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HOSE', 'name' => 'VRE', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'VSC', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HOSE', 'name' => 'VSH', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 23, 'exchange' => 'HOSE', 'name' => 'VTB', 'des' => 'Sản xuất thiết bị truyền thông', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HOSE', 'name' => 'VTO', 'des' => 'Vận tải đường biển, ven biển, hồ lớn', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'AAV', 'des' => 'Bán buôn thực phẩm, tạp hóa và các sản phẩm có liên quan', 'active' => 1],
            [ 'groupId' => 16, 'exchange' => 'HOSE', 'name' => 'ABT', 'des' => 'Sơ chế và đóng gói thủy sản', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'AME', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'AMV', 'des' => 'Bán buôn các thiết bị, vật tư chuyên môn và thương mại', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'API', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HNX', 'name' => 'APS', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HNX', 'name' => 'ART', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 21, 'exchange' => 'HNX', 'name' => 'ATS', 'des' => 'Nhà hàng đầy đủ dịch vụ', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HNX', 'name' => 'BAB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'BBS', 'des' => 'Sản xuất các sản phẩm từ giấy', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'BII', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'BKC', 'des' => 'Khai thác quặng kim loại', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HNX', 'name' => 'BNA', 'des' => 'Sản xuất bánh và bánh mì các loại', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'BPC', 'des' => 'Sản xuất các sản phẩm từ giấy', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'BSI', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HNX', 'name' => 'BVS', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'C69', 'des' => 'Xây dựng công trình khác', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HNX', 'name' => 'CAN', 'des' => 'Bảo quản rau quả và sản xuất thực phẩm chuyên biệt', 'active' => 1],
            [ 'groupId' => 23, 'exchange' => 'HOSE', 'name' => 'CAV', 'des' => 'Sản xuất các thiết bị điện và dụng cụ khác', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'CEO', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'CET', 'des' => 'Sản xuất khác', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HNX', 'name' => 'CIA', 'des' => 'Các cửa hàng hàng hóa khác', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'CLM', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'CMS', 'des' => 'Xây dựng hệ thống tiện ích', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'CSC', 'des' => 'Xây dựng công trình khác', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HNX', 'name' => 'CTC', 'des' => 'Cửa hàng sách, ấn bản và âm nhạc', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'CVN', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HNX', 'name' => 'DDG', 'des' => 'Cung cấp hơi nước và điều hòa không khí', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'DIH', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HNX', 'name' => 'DL1', 'des' => 'Vận tải trung chuyển và vận tải hành khách bằng đường bộ khác', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HNX', 'name' => 'DNC', 'des' => 'Truyền tải, kiểm soát và phân phối điện', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'DNM', 'des' => 'Sản xuất dụng cụ và thiết bị y tế', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HNX', 'name' => 'DS3', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HNX', 'name' => 'DST', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'DTD', 'des' => 'Xây dựng công trình khác', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HNX', 'name' => 'DTK', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HNX', 'name' => 'DXP', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HNX', 'name' => 'EID', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'FID', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HNX', 'name' => 'GLT', 'des' => 'Các loại hình viễn thông khác', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HNX', 'name' => 'HBS', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'HKB', 'des' => 'Bán buôn sản phẩm nuôi trồng thô', 'active' => 1],
            [ 'groupId' => 10, 'exchange' => 'HNX', 'name' => 'HKT', 'des' => 'Trồng trọt các loại cây khác', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HNX', 'name' => 'HMH', 'des' => 'Sắp xếp vận tải hàng hóa', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'HTP', 'des' => 'In ấn', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'HUT', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HNX', 'name' => 'IDC', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'IDJ', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'IDV', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'INN', 'des' => 'Sản xuất các sản phẩm từ giấy', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'ITQ', 'des' => 'Sản xuất sản phẩm kim loại tổng hợp khác', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HNX', 'name' => 'IVS', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'KDM', 'des' => 'Bán buôn đồ nội thất và đồ dùng gia đình', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'KLF', 'des' => 'Đại lý và môi giới bán buôn điện tử', 'active' => 1],
            [ 'groupId' => 23, 'exchange' => 'HNX', 'name' => 'KSD', 'des' => 'Sản xuất đồ điện gia dụng', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'KSQ', 'des' => 'Khai thác quặng kim loại', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'KTT', 'des' => 'Xây dựng hệ thống tiện ích', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'KVC', 'des' => 'Sản xuất sản phẩm kim loại tổng hợp khác', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'L14', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'L18', 'des' => 'Xây dựng hệ thống tiện ích', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'LAF', 'des' => 'Sản xuất các loại thực phẩm khác', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'LIG', 'des' => 'Xây dựng hệ thống tiện ích', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HNX', 'name' => 'MAC', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HNX', 'name' => 'MAS', 'des' => 'Hoạt động hỗ trợ vận tải đường hàng không', 'active' => 1],
            [ 'groupId' => 23, 'exchange' => 'HNX', 'name' => 'MBG', 'des' => 'Sản xuất thiết bị điện chiếu sáng', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HNX', 'name' => 'MBS', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'MST', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'MVB', 'des' => 'Khai thác đá và khoáng sản phi kim', 'active' => 1],
            [ 'groupId' => 11, 'exchange' => 'HNX', 'name' => 'NAG', 'des' => 'Sản xuất hệ thống thông gió, sưởi ấm, điều hòa nhiệt độ và thiết bị làm lạnh', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'NBC', 'des' => 'Khai thác than', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HNX', 'name' => 'NBP', 'des' => 'Phát điện', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HNX', 'name' => 'NBW', 'des' => 'Hệ thống thủy lợi và cung cấp nước', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'NDN', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'NDX', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'NRC', 'des' => 'Đại lý và môi giới bất động sản', 'active' => 1],
            [ 'groupId' => 21, 'exchange' => 'HNX', 'name' => 'OCH', 'des' => 'Chỗ ở cho khách du lịch', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HNX', 'name' => 'ONE', 'des' => 'Các loại hình viễn thông khác', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HOSE', 'name' => 'PAN', 'des' => 'Sản xuất các loại thực phẩm khác', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HNX', 'name' => 'PGS', 'des' => 'Phân phối khí đốt thiên nhiên', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HNX', 'name' => 'PHP', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HNX', 'name' => 'PJC', 'des' => 'Vận tải đường bộ chuyên biệt', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'PLC', 'des' => 'Sản xuất nhựa đường, vật liệu lợp mái và chất bão hòa', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'PMS', 'des' => 'Sản xuất lò hơi, thùng chứa và container vận chuyển', 'active' => 1],
            [ 'groupId' => 24, 'exchange' => 'HNX', 'name' => 'PPE', 'des' => 'Dịch vụ tư vấn xây dựng', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'PPS', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 2, 'exchange' => 'HNX', 'name' => 'PRE', 'des' => 'Hãng bảo hiểm', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'PSD', 'des' => 'Bán buôn các mặt hàng điện, điện tử', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'PSE', 'des' => 'Bán buôn hóa chất và các sản phẩm liên quan', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HNX', 'name' => 'PSI', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 10, 'exchange' => 'HNX', 'name' => 'PSW', 'des' => 'Các hoạt động hỗ trợ cho trồng trọt', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'PTD', 'des' => 'Xây dựng công trình khác', 'active' => 1],
            [ 'groupId' => 2, 'exchange' => 'HNX', 'name' => 'PTI', 'des' => 'Hãng bảo hiểm', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'PV2', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'PVB', 'des' => 'Các hoạt động hỗ trợ cho khai thác dầu và khí đốt', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'PVC', 'des' => 'Các hoạt động hỗ trợ cho khai thác dầu và khí đốt', 'active' => 1],
            [ 'groupId' => 18, 'exchange' => 'HNX', 'name' => 'PVG', 'des' => 'Phân phối khí đốt thiên nhiên', 'active' => 1],
            [ 'groupId' => 2, 'exchange' => 'HNX', 'name' => 'PVI', 'des' => 'Hãng bảo hiểm', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'PVL', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'PVS', 'des' => 'Các hoạt động hỗ trợ cho khai thác dầu và khí đốt', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HOSE', 'name' => 'QBS', 'des' => 'Bán buôn hóa chất và các sản phẩm liên quan', 'active' => 1],
            [ 'groupId' => 11, 'exchange' => 'HNX', 'name' => 'QHD', 'des' => 'Sản xuất thiết bị nông nghiệp, xây dựng và khai khoáng', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'S55', 'des' => 'Xây dựng hệ thống tiện ích', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'S99', 'des' => 'Xây dựng hệ thống tiện ích', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'SCI', 'des' => 'Xây dựng công trình khác', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'SD5', 'des' => 'Xây dựng hệ thống tiện ích', 'active' => 1],
            [ 'groupId' => 21, 'exchange' => 'HNX', 'name' => 'SDA', 'des' => 'Dịch vụ việc làm', 'active' => 1],
            [ 'groupId' => 24, 'exchange' => 'HNX', 'name' => 'SDC', 'des' => 'Dịch vụ thiết kế công nghiệp', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'SDU', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 21, 'exchange' => 'HNX', 'name' => 'SGH', 'des' => 'Chỗ ở cho khách du lịch', 'active' => 1],
            [ 'groupId' => 9, 'exchange' => 'HNX', 'name' => 'SHB', 'des' => 'Trung gian tín dụng có nhận tiền gửi', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HNX', 'name' => 'SHS', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'SIC', 'des' => 'Cho thuê bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'SJC', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 22, 'exchange' => 'HNX', 'name' => 'SMT', 'des' => 'Sản xuất thiết bị truyền thông từ tính và quang học', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'SPI', 'des' => 'Khai thác đá và khoáng sản phi kim', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'SRA', 'des' => 'Bán buôn máy móc, thiết bị và vật tư', 'active' => 1],
            [ 'groupId' => 6, 'exchange' => 'HNX', 'name' => 'SVN', 'des' => 'Kinh doanh vật liệu xây dựng và vật tư liên quan', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'TA9', 'des' => 'Xây dựng cầu đường, đường cao tốc', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HNX', 'name' => 'TAR', 'des' => 'Xay sát các loại hạt và hạt có dầu', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'TC6', 'des' => 'Khai thác than', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'TDN', 'des' => 'Khai thác than', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HNX', 'name' => 'TDT', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HNX', 'name' => 'TFC', 'des' => 'Giết mổ và chế biến thịt động vật', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'THD', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'THT', 'des' => 'Khai thác than', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'TIG', 'des' => 'Các hoạt động liên quan đến bất động sản', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'TKC', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 12, 'exchange' => 'HNX', 'name' => 'TNG', 'des' => 'Sản xuất sản phẩm may mặc công nghiệp', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HNX', 'name' => 'TPH', 'des' => 'Đơn vị xuất bản báo, ấn phẩm, sách và danh mục', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'TTH', 'des' => 'Bán buôn các mặt hàng lâu bền khác', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'TTL', 'des' => 'Xây dựng cầu đường, đường cao tốc', 'active' => 1],
            [ 'groupId' => 21, 'exchange' => 'HNX', 'name' => 'TTT', 'des' => 'Các dịch vụ hỗ trợ khác', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HNX', 'name' => 'TTZ', 'des' => 'Vận tải đường bộ', 'active' => 1],
            [ 'groupId' => 24, 'exchange' => 'HNX', 'name' => 'TV3', 'des' => 'Dịch vụ tư vấn xây dựng', 'active' => 1],
            [ 'groupId' => 24, 'exchange' => 'HNX', 'name' => 'TV4', 'des' => 'Dịch vụ tư vấn xây dựng', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'TVB', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 25, 'exchange' => 'HNX', 'name' => 'TVC', 'des' => 'Các hoạt động đầu tư tài chính khác', 'active' => 1],
            [ 'groupId' => 8, 'exchange' => 'HNX', 'name' => 'TVD', 'des' => 'Khai thác than', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'V12', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'V21', 'des' => 'Xây dựng công trình khác', 'active' => 1],
            [ 'groupId' => 24, 'exchange' => 'HNX', 'name' => 'VAT', 'des' => 'Dịch vụ tư vấn xây dựng', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'VC2', 'des' => 'Xây dựng nhà ở, khu dân cư, cao ốc', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'VC3', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 3, 'exchange' => 'HNX', 'name' => 'VC7', 'des' => 'Phát triển bất động sản', 'active' => 1],
            [ 'groupId' => 21, 'exchange' => 'HNX', 'name' => 'VCM', 'des' => 'Dịch vụ việc làm', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'VE3', 'des' => 'Xây dựng hệ thống tiện ích', 'active' => 1],
            [ 'groupId' => 15, 'exchange' => 'HNX', 'name' => 'VHE', 'des' => 'Sản xuất các loại thực phẩm khác', 'active' => 1],
            [ 'groupId' => 5, 'exchange' => 'HNX', 'name' => 'VIE', 'des' => 'Các loại hình viễn thông khác', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HNX', 'name' => 'VIG', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'VKC', 'des' => 'Bán buôn xe cơ giới và phụ tùng xe cơ giới', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'VMC', 'des' => 'Nhà thầu về nền móng, cấu trúc và bề mặt ngoài', 'active' => 1],
            [ 'groupId' => 20, 'exchange' => 'HNX', 'name' => 'VMI', 'des' => 'Xây dựng công nghiệp nặng và dân dụng khác', 'active' => 1],
            [ 'groupId' => 4, 'exchange' => 'HOSE', 'name' => 'VND', 'des' => 'Môi giới chứng khoán và hàng hóa', 'active' => 1],
            [ 'groupId' => 2, 'exchange' => 'HNX', 'name' => 'VNR', 'des' => 'Hãng bảo hiểm', 'active' => 1],
            [ 'groupId' => 19, 'exchange' => 'HNX', 'name' => 'VSA', 'des' => 'Hoạt động hỗ trợ vận tải đường thủy', 'active' => 1],
            [ 'groupId' => 1, 'exchange' => 'HNX', 'name' => 'VTV', 'des' => 'Bán buôn kim loại và khoáng sản (trừ dầu khí)', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'AAA', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'ACC', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'APH', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'BFC', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'CRC', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'CSV', 'des' => 'Sản xuất hóa chất cơ bản', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'DAG', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 7, 'exchange' => 'HOSE', 'name' => 'DBD', 'des' => 'Sản xuất thuốc và dược phẩm', 'active' => 1],
            [ 'groupId' => 7, 'exchange' => 'HOSE', 'name' => 'DCL', 'des' => 'Sản xuất thuốc và dược phẩm', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'DCM', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'DGC', 'des' => 'Sản xuất hóa chất cơ bản', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'DPM', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'DPR', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'FCM', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông', 'active' => 1],
            [ 'groupId' => 7, 'exchange' => 'HOSE', 'name' => 'FIT', 'des' => 'Sản xuất thuốc và dược phẩm', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'GVR', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'HCD', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'HII', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'HPG', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'HSG', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'HT1', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'NKG', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'PHR', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'PLP', 'des' => 'Sản xuất nhựa, cao su tổng hợp, sợi tổng hợp nhân tạo', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'POM', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HOSE', 'name' => 'RDP', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'TCR', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'TEG', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HOSE', 'name' => 'THG', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông', 'active' => 1],
            [ 'groupId' => 7, 'exchange' => 'HOSE', 'name' => 'TNH', 'des' => 'Các dịch vụ chăm sóc sức khỏe khác', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'ALT', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'BCC', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'BTS', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'CLH', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'CPC', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'DNP', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'DVG', 'des' => 'Sản xuất sơn và chất kết dính', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'GKM', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'HDA', 'des' => 'Sản xuất sơn và chất kết dính', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'HOM', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'LAS', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp', 'active' => 1],
            [ 'groupId' => 7, 'exchange' => 'HNX', 'name' => 'LDP', 'des' => 'Sản xuất thuốc và dược phẩm', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'NHP', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'NSH', 'des' => 'Sản xuất và chế biến nhôm', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'NTP', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'PBP', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'PCE', 'des' => 'Sản xuất thuốc trừ sâu, phân bón và các loại hóa chất nông nghiệp', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'PDB', 'des' => 'Sản xuất xi măng và các sản phẩm bê tông', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'TKU', 'des' => 'Sản xuất và chế biến nhôm', 'active' => 1],
            [ 'groupId' => 14, 'exchange' => 'HNX', 'name' => 'TPP', 'des' => 'Sản xuất các sản phẩm nhựa', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'VCS', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'VGS', 'des' => 'Sản xuất sản phẩm thép từ nguyên liệu thu mua', 'active' => 1],
            [ 'groupId' => 17, 'exchange' => 'HNX', 'name' => 'VHL', 'des' => 'Sản xuất các sản phẩm từ đất sét và vật liệu chịu nhiệt', 'active' => 1],
        ];

        foreach ($rows as $row) {
            $this->db->table('codes')->insert($row);
        }
    }
}
